### ISSUE TITLE
Support output to multiple formats

### ISSUE THREAD

**Issue by sadboyzvone** [sadboyzvone/passthief#1]
The script should be able to output to multiple formats.
This requires that each plugin output should be standardised.
Here are some to name a few:
* [x] Text
* [x] YAML
* [x] JSON
* [x] HTML
* [x] XML
* [x] PDF

If I have more ideas I'll add them here.
The output switch should be called like this:
```
./passthief -o <FILENAME> -f <FORMAT> -m <MODULES>
```
The default output type is text.

**Comment by NulledRoot** [comment]
i can work on both html and xml. PDF idk how to make work but maybe

**Comment by sadboyzvone** [comment]
Go ahead :)
I would do it myself but I have some other projects going on

**Comment by sadboyzvone** [comment]
You may wanna check out pyPdf

**Comment by MarcoBomfim** [comment]
Sup, @sadboyzvone! 

Two questions: 

1. Is this still needed?
2. Is there any specific desired output "visuals" to HTML/XML or PDF, or a simple list (HTML/XML), Text (PDF) would suffice?

**Comment by sadboyzvone** [comment]
Hi @MarcoBomfim 
To answer your questions:
1. Yes!
2. No,I haven't really thought about the visuals so you can make anything you please :)

**Comment by MarcoBomfim** [comment]
Awesome, will work on this on my free time then. Let me know if you have any ideas!

**Comment by Isfaaq** [comment]
Hey. Can you assign the JSON part to me?

**Comment by sadboyzvone** [comment]
@MarcoBomfim if you want to you can take a look at [the modules](https://github.com/sadboyzvone/passthief-modules) as well

**Comment by MarcoBomfim** [comment]
@sadboyzvone awesome, thanks for pointing out the modules, I was trying to figure out how to test it out.

**Comment by sadboyzvone** [comment]
@MarcoBomfim Modules are just Python scripts that are put into the modules directory

**Comment by allEyezOnCode** [comment]
Hi @MarcoBomfim are you still working on it?
@sadboyzvone I can work on html and maybe on XML and PDF, is it still needed ?

**Comment by sadboyzvone** [comment]
If @MarcoBomfim is not already on the XML/PDF path, you have my signal @allEyezOnCode

**Comment by sadboyzvone** [comment]
Great work @allEyezOnCode
